[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/satori/go.uuid"

[[constraint]]
  name = "gopkg.in/src-d/core-retrieval.v0"
  revision = "ad64637aef9aac22f2b9a8568e2ed1f5908c9916"
  source = "https://github.com/src-d/core-retrieval.git"

[[constraint]]
  name = "gopkg.in/src-d/framework.v0"
  revision = "88f5399ee0037158edaef606ec57b7037a80c02a"
  source = "https://github.com/src-d/framework.git"

[[constraint]]
  name = "gopkg.in/src-d/go-billy.v4"
  source = "https://github.com/src-d/go-billy.git"

[[constraint]]
  name = "gopkg.in/src-d/go-errors.v1"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git-fixtures.v3"
  version = "3.1.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  source = "https://github.com/src-d/go-git.git"
  version = "4.2.1"

[[constraint]]
  name = "gopkg.in/src-d/go-kallax.v1"
  version = "1.3.3"
