[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/satori/go.uuid"

[[constraint]]
  name = "gopkg.in/src-d/core-retrieval.v0"
  revision = "16e13cdd66a6398c15c09e6b9ae1ba3f1748298c"
  source = "https://github.com/src-d/core-retrieval.git"

[[constraint]]
  name = "gopkg.in/src-d/framework.v0"
  revision = "bed6b25004fcbc1b034608f01d478aca4135b865"
  source = "https://github.com/src-d/framework.git"

[[constraint]]
  name = "gopkg.in/src-d/go-billy.v4"
  source = "https://github.com/src-d/go-billy.git"

[[constraint]]
  name = "gopkg.in/src-d/go-git-fixtures.v3"
  version = "3.1.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  source = "https://github.com/src-d/go-git.git"
  version = "4.4.0"

[[constraint]]
  name = "gopkg.in/src-d/go-kallax.v1"
  version = "1.3.4"
