[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/satori/go.uuid"

[[constraint]]
  name = "gopkg.in/src-d/core-retrieval.v0"
  revision = "5252fe35bfba3e0635a06ff5633758b53127c588"
  source = "https://github.com/src-d/core-retrieval.git"

[[constraint]]
  name = "gopkg.in/src-d/go-billy.v4"
  source = "https://github.com/src-d/go-billy.git"
  version = "4.2.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git-fixtures.v3"
  version = "3.1.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  source = "https://github.com/src-d/go-git.git"
  revision = "005d5dc961a7053d88da53536f4a5eb4c305529b"

[[constraint]]
  name = "gopkg.in/src-d/go-kallax.v1"
  version = "1.3.4"

[[constraint]]
  name = "gopkg.in/src-d/go-queue.v1"
  version = "~1.0.2"

[[constraint]]
  name = "github.com/lib/pq"
  branch = "master"

[[override]]
  name = "gopkg.in/src-d/go-billy-siva.v4"
  version = "4.2.1"

[prune]
  unused-packages = true
  go-tests = true

  [[prune.project]]
    name = "gopkg.in/src-d/go-git-fixtures.v3"
    unused-packages = false
